### PR TITLE
Fix/offer management bugs

### LINKED ISSUE #365: Offer Limitation handling bug

### PR DESCRIPTION
**Pull request by JustinCast**
# Fix offer management bugs
This PR provides bug fixes in offer management section
# How this should be tested?
- `make run`
- Go to `localhost:3000`
- Create a new offer and see the changes
# Linked issues
closes #365 #278

### CODE REVIEW

**Comment by AngeloCG97** [comment]
review codefactor warnings

**Comment by JeanVegaD** [comment]
image
check this.
when I try to create an offer without limited time

**Comment by AngeloCG97** [comment]
we could validate that the start and end date is before to actually date 

image

**Comment by JustinCast** [comment]
> we could validate that the start and end date is before to current date
> 
> image

Fixed it. This

**Review by JeanVegaD — APPROVED** [review]

**Review by AngeloCG97 — APPROVED** [review]

**Pull request merged**
