### PR TITLE
feature(offers view for donors): view offers by sponsor

### LINKED ISSUE #333: Offer approval design for donor users
As a user, I want to view the offers accepted by a particular lifebank inside their card.

- [x] Coding table for donor users
- [x] Define visualization design for lifebanks cards desktop
- [ ] Apply design to cards

Own: @Edgar097 
Sup: @steph222

### PR DESCRIPTION
**Pull request by Edgar097**
Resolves #333

### What does this PR do?
Show offers by sponsor

### How should this be tested?
- Make run
- More Information (Sponsor)

----

image

### CODE REVIEW

**Review by JustinCast — APPROVED** [review]

**Comment by leisterfrancisco** [comment]
@Edgar097 @steph222 What if we add a tittle that says something like **My Offers**

**Comment by Edgar097** [comment]
> @Edgar097 @steph222 What if we add a tittle that says something like **My Offers**

Solved!

**Review by xavier506 — APPROVED** [review]
LGTM

**Review by leisterfrancisco — APPROVED** [review]
Good work

**Review by steph222 — APPROVED** [review]

**Pull request merged**
