### PR TITLE
Fix/routes terminality

### LINKED ISSUE #793: Show login modal if user goes directly to a route and is not logged in
As a user, I would like to log in any web route without click the login button

### PR DESCRIPTION
**Pull request by Edgar097**
Resolves #793

### What does this PR do?
Check if you can access this routes
without being log in 

- /offers-management
- /offers-approval
- /profile
- /edit-profile
- /history-dashboard

### How should this be tested?
- Make run

### CODE REVIEW

**Review by steph222 — APPROVED** [review]

**Review by leisterfrancisco — CHANGES_REQUESTED** [review]
@Edgar097 the idea with this card is that Login Modal pops up when user goes directly to some of the route this PR specify and for now, you are returning to user to home which is not what we want.

**Review by leisterfrancisco — CHANGES_REQUESTED** [review]
@Edgar097 nice updated, modal is already opening but I'm not being able to make login from some of the direct route that the use can go

**Comment by Edgar097** [comment]
> @Edgar097 nice updated, modal is already opening but I'm not being able to make login from some of the direct route that the use can go

@leisterfrancisco can you specify which routes? please and what type of user you are using to access that route, since some of the routes are not availble for certain type of user.

**Comment by leisterfrancisco** [comment]
> > @Edgar097 nice updated, modal is already opening but I'm not being able to make login from some of the direct route that the use can go
> 
> @leisterfrancisco can you specify which routes? please and what type of user you are using to access that route, since some of the routes are not availble for certain type of user.

@Edgar097  Any route and I taste it under donor profile, at least in my case

**Comment by Edgar097** [comment]
@leisterfrancisco check it out

**Comment by leisterfrancisco** [comment]
@Edgar097  Another thing, after logged in, system is routing to home `/`

**Review by leisterfrancisco — APPROVED** [review]

**Comment by leisterfrancisco** [comment]
reopen this PR until conflicts are solved, by now, I'm going to close it

**Pull request closed without merging**
